import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
})

const inter = Inter({
  weight: "400",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme = "light"
      className={`${poppins.className} ${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-7xl mx-auto">
        <Navbar></Navbar>
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
